//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Projeto.ModelData.Logic.Northwind.MetaData
{
    using System; 
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    
    /// <summary>
    /// Categories class MetaData
    /// </summary>
    public partial class CategoriesMetaData
    {
        [DisplayName("Category ID")]
        [Required(ErrorMessage = "Category ID is required")]
        public int CategoryID { get; set; }
    
        [DisplayName("Category Name")]
        [Required(ErrorMessage = "Category Name is required")]
        [MaxLength(15, ErrorMessage = "Category Name cannot be longer than 15 characters")]
        public string CategoryName { get; set; }
    
        [DisplayName("Description")]
        public string Description { get; set; }
    
        [DisplayName("Picture")]
        public byte[] Picture { get; set; }
    
    }
}
