//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Projeto.ModelData.Logic.Northwind.MetaData
{
    using System; 
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    
    /// <summary>
    /// CustomerDemographics class MetaData
    /// </summary>
    public partial class CustomerDemographicsMetaData
    {
        [DisplayName("Customer Type ID")]
        [Required(ErrorMessage = "Customer Type ID is required")]
        [MaxLength(10, ErrorMessage = "Customer Type ID cannot be longer than 10 characters")]
        public string CustomerTypeID { get; set; }
    
        [DisplayName("Customer Desc")]
        public string CustomerDesc { get; set; }
    
    }
}
