//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Projeto.ModelData.Logic.Northwind.MetaData
{
    using System; 
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    
    /// <summary>
    /// Products class MetaData
    /// </summary>
    public partial class ProductsMetaData
    {
        [DisplayName("Product ID")]
        [Required(ErrorMessage = "Product ID is required")]
        public int ProductID { get; set; }
    
        [DisplayName("Product Name")]
        [Required(ErrorMessage = "Product Name is required")]
        [MaxLength(40, ErrorMessage = "Product Name cannot be longer than 40 characters")]
        public string ProductName { get; set; }
    
        [DisplayName("Supplier ID")]
        public Nullable<int> SupplierID { get; set; }
    
        [DisplayName("Category ID")]
        public Nullable<int> CategoryID { get; set; }
    
        [DisplayName("Quantity Per Unit")]
        [MaxLength(20, ErrorMessage = "Quantity Per Unit cannot be longer than 20 characters")]
        public string QuantityPerUnit { get; set; }
    
        [DisplayName("Unit Price")]
        public Nullable<decimal> UnitPrice { get; set; }
    
        [DisplayName("Units In Stock")]
        public Nullable<short> UnitsInStock { get; set; }
    
        [DisplayName("Units On Order")]
        public Nullable<short> UnitsOnOrder { get; set; }
    
        [DisplayName("Reorder Level")]
        public Nullable<short> ReorderLevel { get; set; }
    
        [DisplayName("Discontinued")]
        [Required(ErrorMessage = "Discontinued is required")]
        public bool Discontinued { get; set; }
    
    }
}
