//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Projeto.ModelData.Logic.Northwind.MetaData
{
    using System; 
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    
    /// <summary>
    /// Region class MetaData
    /// </summary>
    public partial class RegionMetaData
    {
        [DisplayName("Region ID")]
        [Required(ErrorMessage = "Region ID is required")]
        public int RegionID { get; set; }
    
        [DisplayName("Region Description")]
        [Required(ErrorMessage = "Region Description is required")]
        [MaxLength(50, ErrorMessage = "Region Description cannot be longer than 50 characters")]
        public string RegionDescription { get; set; }
    
    }
}
