//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Projeto.ModelData.Logic.Northwind.MetaData;

namespace Projeto.ModelData.Logic.Northwind.Model
{
    using System; 
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using Projeto.ModelData.Logic.Northwind.MetaData;
    
    [Serializable]
    [MetadataType(typeof(CustomerDemographicsMetaData))]
    
    /// <summary>
    /// CustomerDemographics class ModelData
    /// </summary>
    public partial class CustomerDemographics
    {
    
    	public CustomerDemographics()
        {
            this.Customers = new HashSet<Customers>();
        }
    
        public string CustomerTypeID { get; set; }
        public string CustomerDesc { get; set; }
    
        public virtual ICollection<Customers> Customers { get; set; }
    }
}
