//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Projeto.ModelData.Logic.Northwind.MetaData;

namespace Projeto.ModelData.Logic.Northwind.Model
{
    using System; 
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using Projeto.ModelData.Logic.Northwind.MetaData;
    
    [Serializable]
    [MetadataType(typeof(SuppliersMetaData))]
    
    /// <summary>
    /// Suppliers class ModelData
    /// </summary>
    public partial class Suppliers
    {
    
    	public Suppliers()
        {
            this.Products = new HashSet<Products>();
        }
    
        public int SupplierID { get; set; }
        public string CompanyName { get; set; }
        public string ContactName { get; set; }
        public string ContactTitle { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string Region { get; set; }
        public string PostalCode { get; set; }
        public string Country { get; set; }
        public string Phone { get; set; }
        public string Fax { get; set; }
        public string HomePage { get; set; }
    
        public virtual ICollection<Products> Products { get; set; }
    }
}
